### PR TITLE
Add GEO data of china.

### PR DESCRIPTION
**Pull request by chunlinyao**

### CODE REVIEW

**Comment by jonesde** [comment]
This is a very comprehensive data set, which is great. One concern I have with this is how often does it change when getting down to the level of cities and counties?

**Comment by chunlinyao** [comment]
Counties level may changes every 1~2 years.
We can split the file to include only the province level data in mantle. put cities level data somewhere users can found it. Or include all of it and believe someone will maintenance it.

**Comment by jonesde** [comment]
Thank you. I merged it as-is for now and we can see how it works out over time.

**Comment by jonesde** [comment]
On second thought, this is a lot of data in the Geo table and many Mantle users won't need/want it there. Along with the potential maintenance issue this is enough reason to leave the data out by default. It is in the git history and on this pull request so is available, but as you mentioned it might be nice to make it available for download somewhere. I removed the city and county data in commit #4e49d51.

As an idea for that one thing that might be useful in general is localization components that include Geo/etc records, LocalizedMessage records, and so on. If that is something you'd be interested in managing let me know. All you would need to do it create a public GitHub repository (or it could be elsewhere but GitHub is handy) where the root directory if the repo is a Moqui component directory (just like HiveMind, PopCommerce, AuthorizeDotNet, etc) and send me a link and I'll add it to the add-ons list on moqui.org to make it easier for people to find.

Hosting an add-on like this is a good way to get exposure for potential clients and collaborators too.

**Comment by chunlinyao** [comment]
I will create a localization component. It seems difficult to use separate LocalizedMessage file for each component. They are all in localized message table, and we don't have a method to extract l10n message from a component.

**Comment by chunlinyao** [comment]
I created a repository for zh_CN l10n component. The link is `https://github.com/chunlinyao/moqui-zh_CN-addon`

**Comment by jonesde** [comment]
As of the last release this is now listed on the add ons page on moqui.org:

http://www.moqui.org/crust.html

**Pull request merged**
